# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gw6ro4km-gVHeE0ds2i5N9Es-a5JNA2x
"""

import numpy as np
import pandas as pd

def load_data(path: str) -> pd.DataFrame:
    return pd.read_csv(path)

def clean_data(df: pd.DataFrame) -> pd.DataFrame:
    df = df.dropna()
    return df

def remove_erroneous_values(df: pd.DataFrame) -> pd.DataFrame:
    for col in df.columns:
    df = df[df[col] != '?']
    return df