# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gw6ro4km-gVHeE0ds2i5N9Es-a5JNA2x
"""

import matplotlib.pyplot as plt
import seaborn as sns

def dataset_summary(df):
    print(df.info())
    print(df.describe())

def boxplots_for_numerical_features(df):
    # Boxplots for numerical columns
    num_cols = df.select_dtypes(include=['int64', 'float64']).columns
    plt.figure(figsize=(15, 8))
    df[num_cols].boxplot(rot=90)
    plt.title("Boxplot for Numerical Features")
    plt.show()

def plot_distributions(df):
    if 'cnt' in df.columns:
    plt.figure()
    sns.histplot(df['cnt'], kde=True)
    plt.title("Distribution of Bike Rental Count")
    plt.show()

def correlation_plot(df):
    plt.figure(figsize=(10, 8))
    sns.heatmap(df.corr(), cmap="coolwarm", annot=False)
    plt.show()