# -*- coding: utf-8 -*-
"""Feature_Engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gw6ro4km-gVHeE0ds2i5N9Es-a5JNA2x
"""

from sklearn.model_selection import train_test_split

def load_data(path):
    return pd.read_csv(path)

def one_hot_encode(df, column):
    # OHE categorical features
    categorical_cols = ['season', 'holiday', 'workingday', 'weathersit']
    df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
    df = df.replace({True: 1, False: 0})
    return df

def split_xy(df, target):
    X = df.drop('cnt', axis=1)
    y = df['cnt']
    return X, y

def split_data(X, y, test_size=0.2, random_state=42):
    return train_test_split(
        X_tr_cv, X_test, y_tr_cv, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)
        X_train, X_cv, y_train, y_cv = train_test_split(X_tr_cv, y_tr_cv, test_size=0.25, random_state=random_state)
    )