# -*- coding: utf-8 -*-
"""Model_Building.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gw6ro4km-gVHeE0ds2i5N9Es-a5JNA2x
"""

from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

def XGBoost_model(params=None):
    if params is None:
        params = {
            'learning_rate': [0.1, 0.5, 0.8],
            'subsample': [0.6, 0.8, 1.0],
            'colsample_bytree': [0.6, 0.8, 1.0],
            'max_depth': [3, 4, 5]
        }
    xgb = XGBRegressor(
            n_estimators=100,
            objective="reg:squarederror",
            verbosity=0
        )
    return xgb(**params)

def random_search(xgb, params):
    random_search = RandomizedSearchCV(
        xgb,
        param_distributions=params,
        n_iter=10,
        scoring='r2',
        n_jobs=4,
        cv=None
    )
    return random_search